### ISSUE TITLE
Markdown decoration patterns are not applied

### ISSUE THREAD

**Issue by jowitte** [davraamides/todotxt-mode#44]
I tried changing the regex pattern to use for MD tasks: `Todotxtmode: Markdown Decoration Begin Pattern ` but changes do not seem to have any effect.

**Comment by davraamides** [comment]
Can you paste in the expression you tried so I can test it?

On Nov 27, 2021, at 7:23 AM, Jochen Witte ***@***.***> wrote:

﻿
I tried changing the regex pattern to use for MD tasks: Todotxtmode: Markdown Decoration Begin Pattern but changes do not seem to have any effect.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jowitte** [comment]
I just tried to change the name of the section:

                "todotxtmode.markdownDecorationBeginPattern": "^#+\\s+Todos\\s*$",

**Comment by davraamides** [comment]
Can you try restarting VS Code? While that shouldn't be required, I just
tried this and it looks like that regex pattern is being cached in memory
so a change to the user settings isn't seen until a restart.

And also make sure your Markdown file is named in a way that matches the
`markdownFilePattern` setting.

**Comment by jowitte** [comment]
Solved the issue, thanks.
